---
title: CV
---

```{r}
#| label: setup
#| include: false

# Load packages
library(tidyverse)

# Load cv data  
cv <- read_csv("cv.csv")

# Load custom function
create_cv_section <- function(x, include_section = TRUE, 
    include_subsection = TRUE, include_year = TRUE) {
  
  # Start CV section div
  cat(paste0("<div class='cv-", 
    str_replace_all(tolower(x$section[1]), " ", "-"), 
    "'>"))
  cat("\n")
  
  # Create section headers
  if (include_section) {
    cat("<div class='cv-section'>")
    cat(x$section[1])
    cat("</div>")
  }
  
  if (include_subsection) {
    if (!is.na(x$subsection[1])) {
      cat("<div class='cv-subsection'>")
      cat(x$subsection[1])
      cat("</div>")
    }  
  }
  
  # Loop over the rows and extract the relevant information
  for (i in 1:nrow(x)) {
    cat("<div class='cv-item'>")

    # Add year
    if (include_year & !is.na(x$year[i])) {
      cat(paste0("<p class='cv-year'>", x$year[i], "</p>"))
    }
    
    # Check if it is a link
    if (!is.na(x$link[i])) {
      cat(paste0("<a class='cv-content' href=", x$link[i], ">", x$content[i], "</a>"))
    } else {
      cat(paste0("<p class='cv-content'>", x$content[i], "</p>"))
    }
    
    cat("</div>")
  }
  
  # End CV section div
  cat("</div>")
}
```

```{r name, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Name") %>%
  create_cv_section(include_section = FALSE)
```

```{r description, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Description") %>%
  create_cv_section(include_section = FALSE)
```

```{r contact, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Contact") %>%
  create_cv_section(include_section = FALSE)
```

```{r employment, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Employment") %>%
  create_cv_section()
```

```{r education, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Education") %>%
  create_cv_section()
```

```{r publications, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Publications" & subsection == "Stage-1 accepted manuscripts") %>%
  create_cv_section(include_year = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "In preparation") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Preprints") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Peer-reviewed journals") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Book chapters") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Dissertation") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Software") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Publications" & subsection == "Websites") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)
```

```{r presentations, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Presentations" & subsection == "Invited talks") %>%
  create_cv_section(include_year = FALSE)

cv %>%
  filter(section == "Presentations" & subsection == "Conference presentations") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Presentations" & subsection == "Small meetings") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Presentations" & subsection == "Poster presentations") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Presentations" & subsection == "Valorization presentations") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)
```

```{r journals, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Journals" & subsection == "Reviewer") %>%
  create_cv_section()
```

```{r awards, echo = FALSE, results = "asis"}
tibble(
    section = "Awards",
    subsection = NA,
    year = NA,
    link = NA,
    content = "Awards are stupid."
  ) %>%
  create_cv_section()
```

```{r teaching, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Teaching" & subsection == "Courses") %>%
  create_cv_section()

cv %>%
  filter(section == "Teaching" & subsection == "Seminars") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Teaching" & subsection == "Individual lectures") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Teaching" & subsection == "Supervision") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Teaching" & subsection == "Coordination") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Teaching" & subsection == "Other") %>%
  create_cv_section(include_section = FALSE)
```

```{r activities, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Activities" & subsection == "Department") %>%
  create_cv_section(include_year = FALSE)

cv %>%
  filter(section == "Activities" & subsection == "Faculty") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Activities" & subsection == "Workshops") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)

cv %>%
  filter(section == "Activities" & subsection == "Conferences") %>%
  create_cv_section(include_section = FALSE, include_year = FALSE)
```

```{r technical skills, echo = FALSE, results = "asis"}
cv %>%
  filter(section == "Technical skills" & subsection == "Statistics") %>%
  create_cv_section()

cv %>%
  filter(section == "Technical skills" & subsection == "Programming") %>%
  create_cv_section(include_section = FALSE)

cv %>%
  filter(section == "Technical skills" & subsection == "Experimental design") %>%
  create_cv_section(include_section = FALSE)
```
